(ert-deftest signature-default ()
  (with-temp-dir path
    (init)
    (let* ((repo (libgit-repository-open path))
           (config (libgit-repository-config repo)))
      (libgit-config-set-string config "user.name" "Ludwig van")
      (libgit-config-set-string config "user.email" "somewhere@bonn.de")
      (let ((sig (libgit-signature-default repo)))
        (should (libgit-signature-p sig))
        (should (string= "Ludwig van" (libgit-signature-name sig)))
        (should (string= "somewhere@bonn.de" (libgit-signature-email sig)))))))

(ert-deftest signature-now ()
  (let ((sig (libgit-signature-now "Ludwig van Beethoven" "somewhere@bonn.de")))
    (should (libgit-signature-p sig))
    (should (string= "Ludwig van Beethoven" (libgit-signature-name sig)))
    (should (string= "somewhere@bonn.de" (libgit-signature-email sig)))))
