// WARNING!
// This file is generated. Do not edit by hand.
// Instead, edit ../symbols.cfg and run ../gensyms.py

#include "symbols.h"

emacs_value esym_abbreviated_size;
emacs_value esym_abort;
emacs_value esym_added;
emacs_value esym_all;
emacs_value esym_allow_conflicts;
emacs_value esym_always_use_long_format;
emacs_value esym_annotated_commit;
emacs_value esym_app;
emacs_value esym_apply;
emacs_value esym_apply_mailbox;
emacs_value esym_apply_mailbox_or_rebase;
emacs_value esym_args_out_of_range;
emacs_value esym_assq;
emacs_value esym_auto;
emacs_value esym_base;
emacs_value esym_baseline;
emacs_value esym_bisect;
emacs_value esym_blame;
emacs_value esym_blame_hunk;
emacs_value esym_blob;
emacs_value esym_blob_executable;
emacs_value esym_callbacks;
emacs_value esym_car;
emacs_value esym_cdr;
emacs_value esym_certificate_check;
emacs_value esym_check_pathspec;
emacs_value esym_checkout;
emacs_value esym_cherrypick;
emacs_value esym_cherrypick_sequence;
emacs_value esym_commit;
emacs_value esym_config;
emacs_value esym_conflict;
emacs_value esym_conflict_style_diff3;
emacs_value esym_conflict_style_merge;
emacs_value esym_conflicted;
emacs_value esym_cons;
emacs_value esym_consp;
emacs_value esym_context_lines;
emacs_value esym_copied;
emacs_value esym_cred;
emacs_value esym_credentials;
emacs_value esym_current;
emacs_value esym_decode_time;
emacs_value esym_defalias;
emacs_value esym_default;
emacs_value esym_default_directory;
emacs_value esym_default_driver;
emacs_value esym_define_error;
emacs_value esym_deleted;
emacs_value esym_diff;
emacs_value esym_diff_binary;
emacs_value esym_diff_delta;
emacs_value esym_diff_hunk;
emacs_value esym_diff_line;
emacs_value esym_direct;
emacs_value esym_dirty;
emacs_value esym_dirty_suffix;
emacs_value esym_disable_pathspec_match;
emacs_value esym_dont_overwrite_ignored;
emacs_value esym_dont_remove_existing;
emacs_value esym_dont_update_index;
emacs_value esym_dont_write_index;
emacs_value esym_download_tags;
emacs_value esym_emrge;
emacs_value esym_enable_fast_untracked_dirs;
emacs_value esym_encode_time;
emacs_value esym_exclude_submodules;
emacs_value esym_expand_file_name;
emacs_value esym_fail_on_conflict;
emacs_value esym_fastforward;
emacs_value esym_fastforward_only;
emacs_value esym_fetch;
emacs_value esym_file_favor;
emacs_value esym_file_flags;
emacs_value esym_find_renames;
emacs_value esym_first_parent;
emacs_value esym_force;
emacs_value esym_force_binary;
emacs_value esym_force_text;
emacs_value esym_from_owner;
emacs_value esym_functionp;
emacs_value esym_giterr;
emacs_value esym_giterr_callback;
emacs_value esym_giterr_checkout;
emacs_value esym_giterr_cherrypick;
emacs_value esym_giterr_config;
emacs_value esym_giterr_describe;
emacs_value esym_giterr_fetchhead;
emacs_value esym_giterr_filesystem;
emacs_value esym_giterr_filter;
emacs_value esym_giterr_index;
emacs_value esym_giterr_indexer;
emacs_value esym_giterr_invalid;
emacs_value esym_giterr_merge;
emacs_value esym_giterr_net;
emacs_value esym_giterr_nomemory;
emacs_value esym_giterr_object;
emacs_value esym_giterr_odb;
emacs_value esym_giterr_os;
emacs_value esym_giterr_patch;
emacs_value esym_giterr_rebase;
emacs_value esym_giterr_reference;
emacs_value esym_giterr_regex;
emacs_value esym_giterr_repository;
emacs_value esym_giterr_revert;
emacs_value esym_giterr_sha1;
emacs_value esym_giterr_ssh;
emacs_value esym_giterr_ssl;
emacs_value esym_giterr_stash;
emacs_value esym_giterr_submodule;
emacs_value esym_giterr_tag;
emacs_value esym_giterr_thread;
emacs_value esym_giterr_tree;
emacs_value esym_giterr_worktree;
emacs_value esym_giterr_zlib;
emacs_value esym_global;
emacs_value esym_hard;
emacs_value esym_headers;
emacs_value esym_hostkey_libssh2;
emacs_value esym_https;
emacs_value esym_id_abbrev;
emacs_value esym_ignore_case;
emacs_value esym_ignore_filemode;
emacs_value esym_ignore_submodules;
emacs_value esym_ignore_whitespace;
emacs_value esym_ignore_whitespace_change;
emacs_value esym_ignore_whitespace_eol;
emacs_value esym_ignored;
emacs_value esym_in_config;
emacs_value esym_in_head;
emacs_value esym_in_index;
emacs_value esym_in_wd;
emacs_value esym_include_casechange;
emacs_value esym_include_ignored;
emacs_value esym_include_typechange;
emacs_value esym_include_typechange_trees;
emacs_value esym_include_unmodified;
emacs_value esym_include_unreadable;
emacs_value esym_include_unreadable_as_untracked;
emacs_value esym_include_untracked;
emacs_value esym_indent_heuristic;
emacs_value esym_index;
emacs_value esym_index_added;
emacs_value esym_index_and_workdir;
emacs_value esym_index_deleted;
emacs_value esym_index_entry;
emacs_value esym_index_modified;
emacs_value esym_index_new;
emacs_value esym_index_only;
emacs_value esym_index_renamed;
emacs_value esym_index_typechange;
emacs_value esym_insert;
emacs_value esym_integerp;
emacs_value esym_interhunk_lines;
emacs_value esym_last;
emacs_value esym_length;
emacs_value esym_libgit_annotated_commit_p;
emacs_value esym_libgit_blame_hunk_p;
emacs_value esym_libgit_blame_p;
emacs_value esym_libgit_blob_p;
emacs_value esym_libgit_commit_p;
emacs_value esym_libgit_config_p;
emacs_value esym_libgit_cred_p;
emacs_value esym_libgit_diff_binary_p;
emacs_value esym_libgit_diff_delta_p;
emacs_value esym_libgit_diff_hunk_p;
emacs_value esym_libgit_diff_line_p;
emacs_value esym_libgit_diff_p;
emacs_value esym_libgit_index_entry_p;
emacs_value esym_libgit_index_p;
emacs_value esym_libgit_object_p;
emacs_value esym_libgit_reference_p;
emacs_value esym_libgit_reflog_entry_p;
emacs_value esym_libgit_reflog_p;
emacs_value esym_libgit_refspec_p;
emacs_value esym_libgit_remote_p;
emacs_value esym_libgit_repository_p;
emacs_value esym_libgit_revwalk_p;
emacs_value esym_libgit_signature_p;
emacs_value esym_libgit_submodule_p;
emacs_value esym_libgit_tag_p;
emacs_value esym_libgit_transaction_p;
emacs_value esym_libgit_tree_p;
emacs_value esym_libgit_treebuilder_p;
emacs_value esym_link;
emacs_value esym_list;
emacs_value esym_listp;
emacs_value esym_local;
emacs_value esym_max_candidates_tags;
emacs_value esym_max_line;
emacs_value esym_max_size;
emacs_value esym_md5;
emacs_value esym_merge;
emacs_value esym_min_line;
emacs_value esym_minimal;
emacs_value esym_mixed;
emacs_value esym_modified;
emacs_value esym_name_only;
emacs_value esym_name_status;
emacs_value esym_new;
emacs_value esym_new_prefix;
emacs_value esym_newest_commit;
emacs_value esym_nil;
emacs_value esym_no;
emacs_value esym_no_fastforward;
emacs_value esym_no_filemode;
emacs_value esym_no_recursive;
emacs_value esym_no_refresh;
emacs_value esym_no_symlinks;
emacs_value esym_none;
emacs_value esym_normal;
emacs_value esym_notify;
emacs_value esym_notify_when;
emacs_value esym_nsec;
emacs_value esym_object;
emacs_value esym_off;
emacs_value esym_old;
emacs_value esym_old_prefix;
emacs_value esym_oldest_commit;
emacs_value esym_on;
emacs_value esym_ondemand;
emacs_value esym_only_follow_first_parent;
emacs_value esym_ours;
emacs_value esym_patch;
emacs_value esym_patch_header;
emacs_value esym_pathspec;
emacs_value esym_patience;
emacs_value esym_pattern;
emacs_value esym_post;
emacs_value esym_pre;
emacs_value esym_programdata;
emacs_value esym_progress;
emacs_value esym_provide;
emacs_value esym_proxy;
emacs_value esym_prune;
emacs_value esym_push;
emacs_value esym_raw;
emacs_value esym_rebase;
emacs_value esym_rebase_interactive;
emacs_value esym_rebase_merge;
emacs_value esym_recreate_missing;
emacs_value esym_recurse_ignored_dirs;
emacs_value esym_recurse_untracked_dirs;
emacs_value esym_recursion_limit;
emacs_value esym_reference;
emacs_value esym_reflog;
emacs_value esym_reflog_entry;
emacs_value esym_refspec;
emacs_value esym_remote;
emacs_value esym_remove_ignored;
emacs_value esym_remove_untracked;
emacs_value esym_rename_threshold;
emacs_value esym_renamed;
emacs_value esym_renames_from_rewrites;
emacs_value esym_renames_head_to_index;
emacs_value esym_renames_index_to_workdir;
emacs_value esym_repository;
emacs_value esym_reverse;
emacs_value esym_revert;
emacs_value esym_revert_sequence;
emacs_value esym_revwalk;
emacs_value esym_safe;
emacs_value esym_sha1;
emacs_value esym_show_binary;
emacs_value esym_show_commit_oid_as_fallback;
emacs_value esym_show_unmodified;
emacs_value esym_show_untracked_content;
emacs_value esym_sideband_progress;
emacs_value esym_signature;
emacs_value esym_simplify_alnum;
emacs_value esym_skip;
emacs_value esym_skip_binary_check;
emacs_value esym_skip_locked_directories;
emacs_value esym_skip_reuc;
emacs_value esym_skip_unmerged;
emacs_value esym_soft;
emacs_value esym_sort_case_insensitively;
emacs_value esym_sort_case_sensitively;
emacs_value esym_specified;
emacs_value esym_ssh;
emacs_value esym_ssh_custom;
emacs_value esym_ssh_interactive;
emacs_value esym_ssh_key;
emacs_value esym_ssh_memory;
emacs_value esym_strarray;
emacs_value esym_strategy;
emacs_value esym_string_as_unibyte;
emacs_value esym_stringp;
emacs_value esym_style_diff3;
emacs_value esym_style_merge;
emacs_value esym_submodule;
emacs_value esym_symbol_value;
emacs_value esym_symbolic;
emacs_value esym_system;
emacs_value esym_t;
emacs_value esym_tag;
emacs_value esym_tags;
emacs_value esym_target_limit;
emacs_value esym_theirs;
emacs_value esym_threads;
emacs_value esym_time;
emacs_value esym_topological;
emacs_value esym_track_copies_any_commit_copies;
emacs_value esym_track_copies_same_commit_copies;
emacs_value esym_track_copies_same_commit_moves;
emacs_value esym_track_copies_same_file;
emacs_value esym_transaction;
emacs_value esym_transfer_progress;
emacs_value esym_tree;
emacs_value esym_treebuilder;
emacs_value esym_type;
emacs_value esym_typechange;
emacs_value esym_unborn;
emacs_value esym_union;
emacs_value esym_unmodified;
emacs_value esym_unreadable;
emacs_value esym_unspecified;
emacs_value esym_untracked;
emacs_value esym_up_to_date;
emacs_value esym_update_fetchhead;
emacs_value esym_update_index;
emacs_value esym_update_only;
emacs_value esym_update_submodules;
emacs_value esym_update_submodules_if_changed;
emacs_value esym_updated;
emacs_value esym_url;
emacs_value esym_use_mailmap;
emacs_value esym_use_ours;
emacs_value esym_use_theirs;
emacs_value esym_user_ptrp;
emacs_value esym_username;
emacs_value esym_userpass_plaintext;
emacs_value esym_vector;
emacs_value esym_wd_added;
emacs_value esym_wd_deleted;
emacs_value esym_wd_index_modified;
emacs_value esym_wd_modified;
emacs_value esym_wd_uninitialized;
emacs_value esym_wd_untracked;
emacs_value esym_wd_wd_modified;
emacs_value esym_workdir_only;
emacs_value esym_wrong_type_argument;
emacs_value esym_wrong_value_argument;
emacs_value esym_wt_deleted;
emacs_value esym_wt_modified;
emacs_value esym_wt_new;
emacs_value esym_wt_renamed;
emacs_value esym_wt_typechange;
emacs_value esym_wt_unreadable;
emacs_value esym_x509;
emacs_value esym_xdg;
emacs_value esym_yes;

void esyms_init(emacs_env *env)
{
    esym_abbreviated_size = env->make_global_ref(env, env->intern(env, "abbreviated-size"));
    esym_abort = env->make_global_ref(env, env->intern(env, "abort"));
    esym_added = env->make_global_ref(env, env->intern(env, "added"));
    esym_all = env->make_global_ref(env, env->intern(env, "all"));
    esym_allow_conflicts = env->make_global_ref(env, env->intern(env, "allow-conflicts"));
    esym_always_use_long_format = env->make_global_ref(env, env->intern(env, "always-use-long-format"));
    esym_annotated_commit = env->make_global_ref(env, env->intern(env, "annotated-commit"));
    esym_app = env->make_global_ref(env, env->intern(env, "app"));
    esym_apply = env->make_global_ref(env, env->intern(env, "apply"));
    esym_apply_mailbox = env->make_global_ref(env, env->intern(env, "apply-mailbox"));
    esym_apply_mailbox_or_rebase = env->make_global_ref(env, env->intern(env, "apply-mailbox-or-rebase"));
    esym_args_out_of_range = env->make_global_ref(env, env->intern(env, "args-out-of-range"));
    esym_assq = env->make_global_ref(env, env->intern(env, "assq"));
    esym_auto = env->make_global_ref(env, env->intern(env, "auto"));
    esym_base = env->make_global_ref(env, env->intern(env, "base"));
    esym_baseline = env->make_global_ref(env, env->intern(env, "baseline"));
    esym_bisect = env->make_global_ref(env, env->intern(env, "bisect"));
    esym_blame = env->make_global_ref(env, env->intern(env, "blame"));
    esym_blame_hunk = env->make_global_ref(env, env->intern(env, "blame-hunk"));
    esym_blob = env->make_global_ref(env, env->intern(env, "blob"));
    esym_blob_executable = env->make_global_ref(env, env->intern(env, "blob-executable"));
    esym_callbacks = env->make_global_ref(env, env->intern(env, "callbacks"));
    esym_car = env->make_global_ref(env, env->intern(env, "car"));
    esym_cdr = env->make_global_ref(env, env->intern(env, "cdr"));
    esym_certificate_check = env->make_global_ref(env, env->intern(env, "certificate-check"));
    esym_check_pathspec = env->make_global_ref(env, env->intern(env, "check-pathspec"));
    esym_checkout = env->make_global_ref(env, env->intern(env, "checkout"));
    esym_cherrypick = env->make_global_ref(env, env->intern(env, "cherrypick"));
    esym_cherrypick_sequence = env->make_global_ref(env, env->intern(env, "cherrypick-sequence"));
    esym_commit = env->make_global_ref(env, env->intern(env, "commit"));
    esym_config = env->make_global_ref(env, env->intern(env, "config"));
    esym_conflict = env->make_global_ref(env, env->intern(env, "conflict"));
    esym_conflict_style_diff3 = env->make_global_ref(env, env->intern(env, "conflict-style-diff3"));
    esym_conflict_style_merge = env->make_global_ref(env, env->intern(env, "conflict-style-merge"));
    esym_conflicted = env->make_global_ref(env, env->intern(env, "conflicted"));
    esym_cons = env->make_global_ref(env, env->intern(env, "cons"));
    esym_consp = env->make_global_ref(env, env->intern(env, "consp"));
    esym_context_lines = env->make_global_ref(env, env->intern(env, "context-lines"));
    esym_copied = env->make_global_ref(env, env->intern(env, "copied"));
    esym_cred = env->make_global_ref(env, env->intern(env, "cred"));
    esym_credentials = env->make_global_ref(env, env->intern(env, "credentials"));
    esym_current = env->make_global_ref(env, env->intern(env, "current"));
    esym_decode_time = env->make_global_ref(env, env->intern(env, "decode-time"));
    esym_defalias = env->make_global_ref(env, env->intern(env, "defalias"));
    esym_default = env->make_global_ref(env, env->intern(env, "default"));
    esym_default_directory = env->make_global_ref(env, env->intern(env, "default-directory"));
    esym_default_driver = env->make_global_ref(env, env->intern(env, "default-driver"));
    esym_define_error = env->make_global_ref(env, env->intern(env, "define-error"));
    esym_deleted = env->make_global_ref(env, env->intern(env, "deleted"));
    esym_diff = env->make_global_ref(env, env->intern(env, "diff"));
    esym_diff_binary = env->make_global_ref(env, env->intern(env, "diff-binary"));
    esym_diff_delta = env->make_global_ref(env, env->intern(env, "diff-delta"));
    esym_diff_hunk = env->make_global_ref(env, env->intern(env, "diff-hunk"));
    esym_diff_line = env->make_global_ref(env, env->intern(env, "diff-line"));
    esym_direct = env->make_global_ref(env, env->intern(env, "direct"));
    esym_dirty = env->make_global_ref(env, env->intern(env, "dirty"));
    esym_dirty_suffix = env->make_global_ref(env, env->intern(env, "dirty-suffix"));
    esym_disable_pathspec_match = env->make_global_ref(env, env->intern(env, "disable-pathspec-match"));
    esym_dont_overwrite_ignored = env->make_global_ref(env, env->intern(env, "dont-overwrite-ignored"));
    esym_dont_remove_existing = env->make_global_ref(env, env->intern(env, "dont-remove-existing"));
    esym_dont_update_index = env->make_global_ref(env, env->intern(env, "dont-update-index"));
    esym_dont_write_index = env->make_global_ref(env, env->intern(env, "dont-write-index"));
    esym_download_tags = env->make_global_ref(env, env->intern(env, "download-tags"));
    esym_emrge = env->make_global_ref(env, env->intern(env, "emrge"));
    esym_enable_fast_untracked_dirs = env->make_global_ref(env, env->intern(env, "enable-fast-untracked-dirs"));
    esym_encode_time = env->make_global_ref(env, env->intern(env, "encode-time"));
    esym_exclude_submodules = env->make_global_ref(env, env->intern(env, "exclude-submodules"));
    esym_expand_file_name = env->make_global_ref(env, env->intern(env, "expand-file-name"));
    esym_fail_on_conflict = env->make_global_ref(env, env->intern(env, "fail-on-conflict"));
    esym_fastforward = env->make_global_ref(env, env->intern(env, "fastforward"));
    esym_fastforward_only = env->make_global_ref(env, env->intern(env, "fastforward-only"));
    esym_fetch = env->make_global_ref(env, env->intern(env, "fetch"));
    esym_file_favor = env->make_global_ref(env, env->intern(env, "file-favor"));
    esym_file_flags = env->make_global_ref(env, env->intern(env, "file-flags"));
    esym_find_renames = env->make_global_ref(env, env->intern(env, "find-renames"));
    esym_first_parent = env->make_global_ref(env, env->intern(env, "first-parent"));
    esym_force = env->make_global_ref(env, env->intern(env, "force"));
    esym_force_binary = env->make_global_ref(env, env->intern(env, "force-binary"));
    esym_force_text = env->make_global_ref(env, env->intern(env, "force-text"));
    esym_from_owner = env->make_global_ref(env, env->intern(env, "from-owner"));
    esym_functionp = env->make_global_ref(env, env->intern(env, "functionp"));
    esym_giterr = env->make_global_ref(env, env->intern(env, "giterr"));
    esym_giterr_callback = env->make_global_ref(env, env->intern(env, "giterr-callback"));
    esym_giterr_checkout = env->make_global_ref(env, env->intern(env, "giterr-checkout"));
    esym_giterr_cherrypick = env->make_global_ref(env, env->intern(env, "giterr-cherrypick"));
    esym_giterr_config = env->make_global_ref(env, env->intern(env, "giterr-config"));
    esym_giterr_describe = env->make_global_ref(env, env->intern(env, "giterr-describe"));
    esym_giterr_fetchhead = env->make_global_ref(env, env->intern(env, "giterr-fetchhead"));
    esym_giterr_filesystem = env->make_global_ref(env, env->intern(env, "giterr-filesystem"));
    esym_giterr_filter = env->make_global_ref(env, env->intern(env, "giterr-filter"));
    esym_giterr_index = env->make_global_ref(env, env->intern(env, "giterr-index"));
    esym_giterr_indexer = env->make_global_ref(env, env->intern(env, "giterr-indexer"));
    esym_giterr_invalid = env->make_global_ref(env, env->intern(env, "giterr-invalid"));
    esym_giterr_merge = env->make_global_ref(env, env->intern(env, "giterr-merge"));
    esym_giterr_net = env->make_global_ref(env, env->intern(env, "giterr-net"));
    esym_giterr_nomemory = env->make_global_ref(env, env->intern(env, "giterr-nomemory"));
    esym_giterr_object = env->make_global_ref(env, env->intern(env, "giterr-object"));
    esym_giterr_odb = env->make_global_ref(env, env->intern(env, "giterr-odb"));
    esym_giterr_os = env->make_global_ref(env, env->intern(env, "giterr-os"));
    esym_giterr_patch = env->make_global_ref(env, env->intern(env, "giterr-patch"));
    esym_giterr_rebase = env->make_global_ref(env, env->intern(env, "giterr-rebase"));
    esym_giterr_reference = env->make_global_ref(env, env->intern(env, "giterr-reference"));
    esym_giterr_regex = env->make_global_ref(env, env->intern(env, "giterr-regex"));
    esym_giterr_repository = env->make_global_ref(env, env->intern(env, "giterr-repository"));
    esym_giterr_revert = env->make_global_ref(env, env->intern(env, "giterr-revert"));
    esym_giterr_sha1 = env->make_global_ref(env, env->intern(env, "giterr-sha1"));
    esym_giterr_ssh = env->make_global_ref(env, env->intern(env, "giterr-ssh"));
    esym_giterr_ssl = env->make_global_ref(env, env->intern(env, "giterr-ssl"));
    esym_giterr_stash = env->make_global_ref(env, env->intern(env, "giterr-stash"));
    esym_giterr_submodule = env->make_global_ref(env, env->intern(env, "giterr-submodule"));
    esym_giterr_tag = env->make_global_ref(env, env->intern(env, "giterr-tag"));
    esym_giterr_thread = env->make_global_ref(env, env->intern(env, "giterr-thread"));
    esym_giterr_tree = env->make_global_ref(env, env->intern(env, "giterr-tree"));
    esym_giterr_worktree = env->make_global_ref(env, env->intern(env, "giterr-worktree"));
    esym_giterr_zlib = env->make_global_ref(env, env->intern(env, "giterr-zlib"));
    esym_global = env->make_global_ref(env, env->intern(env, "global"));
    esym_hard = env->make_global_ref(env, env->intern(env, "hard"));
    esym_headers = env->make_global_ref(env, env->intern(env, "headers"));
    esym_hostkey_libssh2 = env->make_global_ref(env, env->intern(env, "hostkey-libssh2"));
    esym_https = env->make_global_ref(env, env->intern(env, "https"));
    esym_id_abbrev = env->make_global_ref(env, env->intern(env, "id-abbrev"));
    esym_ignore_case = env->make_global_ref(env, env->intern(env, "ignore-case"));
    esym_ignore_filemode = env->make_global_ref(env, env->intern(env, "ignore-filemode"));
    esym_ignore_submodules = env->make_global_ref(env, env->intern(env, "ignore-submodules"));
    esym_ignore_whitespace = env->make_global_ref(env, env->intern(env, "ignore-whitespace"));
    esym_ignore_whitespace_change = env->make_global_ref(env, env->intern(env, "ignore-whitespace-change"));
    esym_ignore_whitespace_eol = env->make_global_ref(env, env->intern(env, "ignore-whitespace-eol"));
    esym_ignored = env->make_global_ref(env, env->intern(env, "ignored"));
    esym_in_config = env->make_global_ref(env, env->intern(env, "in-config"));
    esym_in_head = env->make_global_ref(env, env->intern(env, "in-head"));
    esym_in_index = env->make_global_ref(env, env->intern(env, "in-index"));
    esym_in_wd = env->make_global_ref(env, env->intern(env, "in-wd"));
    esym_include_casechange = env->make_global_ref(env, env->intern(env, "include-casechange"));
    esym_include_ignored = env->make_global_ref(env, env->intern(env, "include-ignored"));
    esym_include_typechange = env->make_global_ref(env, env->intern(env, "include-typechange"));
    esym_include_typechange_trees = env->make_global_ref(env, env->intern(env, "include-typechange-trees"));
    esym_include_unmodified = env->make_global_ref(env, env->intern(env, "include-unmodified"));
    esym_include_unreadable = env->make_global_ref(env, env->intern(env, "include-unreadable"));
    esym_include_unreadable_as_untracked = env->make_global_ref(env, env->intern(env, "include-unreadable-as-untracked"));
    esym_include_untracked = env->make_global_ref(env, env->intern(env, "include-untracked"));
    esym_indent_heuristic = env->make_global_ref(env, env->intern(env, "indent-heuristic"));
    esym_index = env->make_global_ref(env, env->intern(env, "index"));
    esym_index_added = env->make_global_ref(env, env->intern(env, "index-added"));
    esym_index_and_workdir = env->make_global_ref(env, env->intern(env, "index-and-workdir"));
    esym_index_deleted = env->make_global_ref(env, env->intern(env, "index-deleted"));
    esym_index_entry = env->make_global_ref(env, env->intern(env, "index-entry"));
    esym_index_modified = env->make_global_ref(env, env->intern(env, "index-modified"));
    esym_index_new = env->make_global_ref(env, env->intern(env, "index-new"));
    esym_index_only = env->make_global_ref(env, env->intern(env, "index-only"));
    esym_index_renamed = env->make_global_ref(env, env->intern(env, "index-renamed"));
    esym_index_typechange = env->make_global_ref(env, env->intern(env, "index-typechange"));
    esym_insert = env->make_global_ref(env, env->intern(env, "insert"));
    esym_integerp = env->make_global_ref(env, env->intern(env, "integerp"));
    esym_interhunk_lines = env->make_global_ref(env, env->intern(env, "interhunk-lines"));
    esym_last = env->make_global_ref(env, env->intern(env, "last"));
    esym_length = env->make_global_ref(env, env->intern(env, "length"));
    esym_libgit_annotated_commit_p = env->make_global_ref(env, env->intern(env, "libgit-annotated-commit-p"));
    esym_libgit_blame_hunk_p = env->make_global_ref(env, env->intern(env, "libgit-blame-hunk-p"));
    esym_libgit_blame_p = env->make_global_ref(env, env->intern(env, "libgit-blame-p"));
    esym_libgit_blob_p = env->make_global_ref(env, env->intern(env, "libgit-blob-p"));
    esym_libgit_commit_p = env->make_global_ref(env, env->intern(env, "libgit-commit-p"));
    esym_libgit_config_p = env->make_global_ref(env, env->intern(env, "libgit-config-p"));
    esym_libgit_cred_p = env->make_global_ref(env, env->intern(env, "libgit-cred-p"));
    esym_libgit_diff_binary_p = env->make_global_ref(env, env->intern(env, "libgit-diff-binary-p"));
    esym_libgit_diff_delta_p = env->make_global_ref(env, env->intern(env, "libgit-diff-delta-p"));
    esym_libgit_diff_hunk_p = env->make_global_ref(env, env->intern(env, "libgit-diff-hunk-p"));
    esym_libgit_diff_line_p = env->make_global_ref(env, env->intern(env, "libgit-diff-line-p"));
    esym_libgit_diff_p = env->make_global_ref(env, env->intern(env, "libgit-diff-p"));
    esym_libgit_index_entry_p = env->make_global_ref(env, env->intern(env, "libgit-index-entry-p"));
    esym_libgit_index_p = env->make_global_ref(env, env->intern(env, "libgit-index-p"));
    esym_libgit_object_p = env->make_global_ref(env, env->intern(env, "libgit-object-p"));
    esym_libgit_reference_p = env->make_global_ref(env, env->intern(env, "libgit-reference-p"));
    esym_libgit_reflog_entry_p = env->make_global_ref(env, env->intern(env, "libgit-reflog-entry-p"));
    esym_libgit_reflog_p = env->make_global_ref(env, env->intern(env, "libgit-reflog-p"));
    esym_libgit_refspec_p = env->make_global_ref(env, env->intern(env, "libgit-refspec-p"));
    esym_libgit_remote_p = env->make_global_ref(env, env->intern(env, "libgit-remote-p"));
    esym_libgit_repository_p = env->make_global_ref(env, env->intern(env, "libgit-repository-p"));
    esym_libgit_revwalk_p = env->make_global_ref(env, env->intern(env, "libgit-revwalk-p"));
    esym_libgit_signature_p = env->make_global_ref(env, env->intern(env, "libgit-signature-p"));
    esym_libgit_submodule_p = env->make_global_ref(env, env->intern(env, "libgit-submodule-p"));
    esym_libgit_tag_p = env->make_global_ref(env, env->intern(env, "libgit-tag-p"));
    esym_libgit_transaction_p = env->make_global_ref(env, env->intern(env, "libgit-transaction-p"));
    esym_libgit_tree_p = env->make_global_ref(env, env->intern(env, "libgit-tree-p"));
    esym_libgit_treebuilder_p = env->make_global_ref(env, env->intern(env, "libgit-treebuilder-p"));
    esym_link = env->make_global_ref(env, env->intern(env, "link"));
    esym_list = env->make_global_ref(env, env->intern(env, "list"));
    esym_listp = env->make_global_ref(env, env->intern(env, "listp"));
    esym_local = env->make_global_ref(env, env->intern(env, "local"));
    esym_max_candidates_tags = env->make_global_ref(env, env->intern(env, "max-candidates-tags"));
    esym_max_line = env->make_global_ref(env, env->intern(env, "max-line"));
    esym_max_size = env->make_global_ref(env, env->intern(env, "max-size"));
    esym_md5 = env->make_global_ref(env, env->intern(env, "md5"));
    esym_merge = env->make_global_ref(env, env->intern(env, "merge"));
    esym_min_line = env->make_global_ref(env, env->intern(env, "min-line"));
    esym_minimal = env->make_global_ref(env, env->intern(env, "minimal"));
    esym_mixed = env->make_global_ref(env, env->intern(env, "mixed"));
    esym_modified = env->make_global_ref(env, env->intern(env, "modified"));
    esym_name_only = env->make_global_ref(env, env->intern(env, "name-only"));
    esym_name_status = env->make_global_ref(env, env->intern(env, "name-status"));
    esym_new = env->make_global_ref(env, env->intern(env, "new"));
    esym_new_prefix = env->make_global_ref(env, env->intern(env, "new-prefix"));
    esym_newest_commit = env->make_global_ref(env, env->intern(env, "newest-commit"));
    esym_nil = env->make_global_ref(env, env->intern(env, "nil"));
    esym_no = env->make_global_ref(env, env->intern(env, "no"));
    esym_no_fastforward = env->make_global_ref(env, env->intern(env, "no-fastforward"));
    esym_no_filemode = env->make_global_ref(env, env->intern(env, "no-filemode"));
    esym_no_recursive = env->make_global_ref(env, env->intern(env, "no-recursive"));
    esym_no_refresh = env->make_global_ref(env, env->intern(env, "no-refresh"));
    esym_no_symlinks = env->make_global_ref(env, env->intern(env, "no-symlinks"));
    esym_none = env->make_global_ref(env, env->intern(env, "none"));
    esym_normal = env->make_global_ref(env, env->intern(env, "normal"));
    esym_notify = env->make_global_ref(env, env->intern(env, "notify"));
    esym_notify_when = env->make_global_ref(env, env->intern(env, "notify-when"));
    esym_nsec = env->make_global_ref(env, env->intern(env, "nsec"));
    esym_object = env->make_global_ref(env, env->intern(env, "object"));
    esym_off = env->make_global_ref(env, env->intern(env, "off"));
    esym_old = env->make_global_ref(env, env->intern(env, "old"));
    esym_old_prefix = env->make_global_ref(env, env->intern(env, "old-prefix"));
    esym_oldest_commit = env->make_global_ref(env, env->intern(env, "oldest-commit"));
    esym_on = env->make_global_ref(env, env->intern(env, "on"));
    esym_ondemand = env->make_global_ref(env, env->intern(env, "ondemand"));
    esym_only_follow_first_parent = env->make_global_ref(env, env->intern(env, "only-follow-first-parent"));
    esym_ours = env->make_global_ref(env, env->intern(env, "ours"));
    esym_patch = env->make_global_ref(env, env->intern(env, "patch"));
    esym_patch_header = env->make_global_ref(env, env->intern(env, "patch-header"));
    esym_pathspec = env->make_global_ref(env, env->intern(env, "pathspec"));
    esym_patience = env->make_global_ref(env, env->intern(env, "patience"));
    esym_pattern = env->make_global_ref(env, env->intern(env, "pattern"));
    esym_post = env->make_global_ref(env, env->intern(env, "post"));
    esym_pre = env->make_global_ref(env, env->intern(env, "pre"));
    esym_programdata = env->make_global_ref(env, env->intern(env, "programdata"));
    esym_progress = env->make_global_ref(env, env->intern(env, "progress"));
    esym_provide = env->make_global_ref(env, env->intern(env, "provide"));
    esym_proxy = env->make_global_ref(env, env->intern(env, "proxy"));
    esym_prune = env->make_global_ref(env, env->intern(env, "prune"));
    esym_push = env->make_global_ref(env, env->intern(env, "push"));
    esym_raw = env->make_global_ref(env, env->intern(env, "raw"));
    esym_rebase = env->make_global_ref(env, env->intern(env, "rebase"));
    esym_rebase_interactive = env->make_global_ref(env, env->intern(env, "rebase-interactive"));
    esym_rebase_merge = env->make_global_ref(env, env->intern(env, "rebase-merge"));
    esym_recreate_missing = env->make_global_ref(env, env->intern(env, "recreate-missing"));
    esym_recurse_ignored_dirs = env->make_global_ref(env, env->intern(env, "recurse-ignored-dirs"));
    esym_recurse_untracked_dirs = env->make_global_ref(env, env->intern(env, "recurse-untracked-dirs"));
    esym_recursion_limit = env->make_global_ref(env, env->intern(env, "recursion-limit"));
    esym_reference = env->make_global_ref(env, env->intern(env, "reference"));
    esym_reflog = env->make_global_ref(env, env->intern(env, "reflog"));
    esym_reflog_entry = env->make_global_ref(env, env->intern(env, "reflog-entry"));
    esym_refspec = env->make_global_ref(env, env->intern(env, "refspec"));
    esym_remote = env->make_global_ref(env, env->intern(env, "remote"));
    esym_remove_ignored = env->make_global_ref(env, env->intern(env, "remove-ignored"));
    esym_remove_untracked = env->make_global_ref(env, env->intern(env, "remove-untracked"));
    esym_rename_threshold = env->make_global_ref(env, env->intern(env, "rename-threshold"));
    esym_renamed = env->make_global_ref(env, env->intern(env, "renamed"));
    esym_renames_from_rewrites = env->make_global_ref(env, env->intern(env, "renames-from-rewrites"));
    esym_renames_head_to_index = env->make_global_ref(env, env->intern(env, "renames-head-to-index"));
    esym_renames_index_to_workdir = env->make_global_ref(env, env->intern(env, "renames-index-to-workdir"));
    esym_repository = env->make_global_ref(env, env->intern(env, "repository"));
    esym_reverse = env->make_global_ref(env, env->intern(env, "reverse"));
    esym_revert = env->make_global_ref(env, env->intern(env, "revert"));
    esym_revert_sequence = env->make_global_ref(env, env->intern(env, "revert-sequence"));
    esym_revwalk = env->make_global_ref(env, env->intern(env, "revwalk"));
    esym_safe = env->make_global_ref(env, env->intern(env, "safe"));
    esym_sha1 = env->make_global_ref(env, env->intern(env, "sha1"));
    esym_show_binary = env->make_global_ref(env, env->intern(env, "show-binary"));
    esym_show_commit_oid_as_fallback = env->make_global_ref(env, env->intern(env, "show-commit-oid-as-fallback"));
    esym_show_unmodified = env->make_global_ref(env, env->intern(env, "show-unmodified"));
    esym_show_untracked_content = env->make_global_ref(env, env->intern(env, "show-untracked-content"));
    esym_sideband_progress = env->make_global_ref(env, env->intern(env, "sideband-progress"));
    esym_signature = env->make_global_ref(env, env->intern(env, "signature"));
    esym_simplify_alnum = env->make_global_ref(env, env->intern(env, "simplify-alnum"));
    esym_skip = env->make_global_ref(env, env->intern(env, "skip"));
    esym_skip_binary_check = env->make_global_ref(env, env->intern(env, "skip-binary-check"));
    esym_skip_locked_directories = env->make_global_ref(env, env->intern(env, "skip-locked-directories"));
    esym_skip_reuc = env->make_global_ref(env, env->intern(env, "skip-reuc"));
    esym_skip_unmerged = env->make_global_ref(env, env->intern(env, "skip-unmerged"));
    esym_soft = env->make_global_ref(env, env->intern(env, "soft"));
    esym_sort_case_insensitively = env->make_global_ref(env, env->intern(env, "sort-case-insensitively"));
    esym_sort_case_sensitively = env->make_global_ref(env, env->intern(env, "sort-case-sensitively"));
    esym_specified = env->make_global_ref(env, env->intern(env, "specified"));
    esym_ssh = env->make_global_ref(env, env->intern(env, "ssh"));
    esym_ssh_custom = env->make_global_ref(env, env->intern(env, "ssh-custom"));
    esym_ssh_interactive = env->make_global_ref(env, env->intern(env, "ssh-interactive"));
    esym_ssh_key = env->make_global_ref(env, env->intern(env, "ssh-key"));
    esym_ssh_memory = env->make_global_ref(env, env->intern(env, "ssh-memory"));
    esym_strarray = env->make_global_ref(env, env->intern(env, "strarray"));
    esym_strategy = env->make_global_ref(env, env->intern(env, "strategy"));
    esym_string_as_unibyte = env->make_global_ref(env, env->intern(env, "string-as-unibyte"));
    esym_stringp = env->make_global_ref(env, env->intern(env, "stringp"));
    esym_style_diff3 = env->make_global_ref(env, env->intern(env, "style-diff3"));
    esym_style_merge = env->make_global_ref(env, env->intern(env, "style-merge"));
    esym_submodule = env->make_global_ref(env, env->intern(env, "submodule"));
    esym_symbol_value = env->make_global_ref(env, env->intern(env, "symbol-value"));
    esym_symbolic = env->make_global_ref(env, env->intern(env, "symbolic"));
    esym_system = env->make_global_ref(env, env->intern(env, "system"));
    esym_t = env->make_global_ref(env, env->intern(env, "t"));
    esym_tag = env->make_global_ref(env, env->intern(env, "tag"));
    esym_tags = env->make_global_ref(env, env->intern(env, "tags"));
    esym_target_limit = env->make_global_ref(env, env->intern(env, "target-limit"));
    esym_theirs = env->make_global_ref(env, env->intern(env, "theirs"));
    esym_threads = env->make_global_ref(env, env->intern(env, "threads"));
    esym_time = env->make_global_ref(env, env->intern(env, "time"));
    esym_topological = env->make_global_ref(env, env->intern(env, "topological"));
    esym_track_copies_any_commit_copies = env->make_global_ref(env, env->intern(env, "track-copies-any-commit-copies"));
    esym_track_copies_same_commit_copies = env->make_global_ref(env, env->intern(env, "track-copies-same-commit-copies"));
    esym_track_copies_same_commit_moves = env->make_global_ref(env, env->intern(env, "track-copies-same-commit-moves"));
    esym_track_copies_same_file = env->make_global_ref(env, env->intern(env, "track-copies-same-file"));
    esym_transaction = env->make_global_ref(env, env->intern(env, "transaction"));
    esym_transfer_progress = env->make_global_ref(env, env->intern(env, "transfer-progress"));
    esym_tree = env->make_global_ref(env, env->intern(env, "tree"));
    esym_treebuilder = env->make_global_ref(env, env->intern(env, "treebuilder"));
    esym_type = env->make_global_ref(env, env->intern(env, "type"));
    esym_typechange = env->make_global_ref(env, env->intern(env, "typechange"));
    esym_unborn = env->make_global_ref(env, env->intern(env, "unborn"));
    esym_union = env->make_global_ref(env, env->intern(env, "union"));
    esym_unmodified = env->make_global_ref(env, env->intern(env, "unmodified"));
    esym_unreadable = env->make_global_ref(env, env->intern(env, "unreadable"));
    esym_unspecified = env->make_global_ref(env, env->intern(env, "unspecified"));
    esym_untracked = env->make_global_ref(env, env->intern(env, "untracked"));
    esym_up_to_date = env->make_global_ref(env, env->intern(env, "up-to-date"));
    esym_update_fetchhead = env->make_global_ref(env, env->intern(env, "update-fetchhead"));
    esym_update_index = env->make_global_ref(env, env->intern(env, "update-index"));
    esym_update_only = env->make_global_ref(env, env->intern(env, "update-only"));
    esym_update_submodules = env->make_global_ref(env, env->intern(env, "update-submodules"));
    esym_update_submodules_if_changed = env->make_global_ref(env, env->intern(env, "update-submodules-if-changed"));
    esym_updated = env->make_global_ref(env, env->intern(env, "updated"));
    esym_url = env->make_global_ref(env, env->intern(env, "url"));
    esym_use_mailmap = env->make_global_ref(env, env->intern(env, "use-mailmap"));
    esym_use_ours = env->make_global_ref(env, env->intern(env, "use-ours"));
    esym_use_theirs = env->make_global_ref(env, env->intern(env, "use-theirs"));
    esym_user_ptrp = env->make_global_ref(env, env->intern(env, "user-ptrp"));
    esym_username = env->make_global_ref(env, env->intern(env, "username"));
    esym_userpass_plaintext = env->make_global_ref(env, env->intern(env, "userpass-plaintext"));
    esym_vector = env->make_global_ref(env, env->intern(env, "vector"));
    esym_wd_added = env->make_global_ref(env, env->intern(env, "wd-added"));
    esym_wd_deleted = env->make_global_ref(env, env->intern(env, "wd-deleted"));
    esym_wd_index_modified = env->make_global_ref(env, env->intern(env, "wd-index-modified"));
    esym_wd_modified = env->make_global_ref(env, env->intern(env, "wd-modified"));
    esym_wd_uninitialized = env->make_global_ref(env, env->intern(env, "wd-uninitialized"));
    esym_wd_untracked = env->make_global_ref(env, env->intern(env, "wd-untracked"));
    esym_wd_wd_modified = env->make_global_ref(env, env->intern(env, "wd-wd-modified"));
    esym_workdir_only = env->make_global_ref(env, env->intern(env, "workdir-only"));
    esym_wrong_type_argument = env->make_global_ref(env, env->intern(env, "wrong-type-argument"));
    esym_wrong_value_argument = env->make_global_ref(env, env->intern(env, "wrong-value-argument"));
    esym_wt_deleted = env->make_global_ref(env, env->intern(env, "wt-deleted"));
    esym_wt_modified = env->make_global_ref(env, env->intern(env, "wt-modified"));
    esym_wt_new = env->make_global_ref(env, env->intern(env, "wt-new"));
    esym_wt_renamed = env->make_global_ref(env, env->intern(env, "wt-renamed"));
    esym_wt_typechange = env->make_global_ref(env, env->intern(env, "wt-typechange"));
    esym_wt_unreadable = env->make_global_ref(env, env->intern(env, "wt-unreadable"));
    esym_x509 = env->make_global_ref(env, env->intern(env, "x509"));
    esym_xdg = env->make_global_ref(env, env->intern(env, "xdg"));
    esym_yes = env->make_global_ref(env, env->intern(env, "yes"));
}
