// WARNING!
// This file is generated. Do not edit by hand.
// Instead, edit ../symbols.cfg and run ../gensyms.py

#include "emacs-module.h"
#include "git2.h"

#ifndef SYMBOLS_H
#define SYMBOLS_H

typedef union {
    git_blame_flag_t blame_flag;
    git_branch_t branch;
    git_cert_ssh_t cert_ssh;
    git_cert_t cert;
    git_checkout_notify_t checkout_notify;
    git_checkout_strategy_t checkout_strategy;
    git_config_level_t config_level;
    git_credtype_t credtype;
    git_describe_strategy_t describe_strategy;
    git_delta_t delta;
    git_diff_format_t diff_format;
    git_diff_option_t diff_option;
    git_direction direction;
    git_error_t error;
    git_feature_t feature;
    git_fetch_prune_t fetch_prune;
    git_filemode_t filemode;
    git_index_add_option_t index_add_option;
    git_indexcap_t indexcap;
    git_merge_analysis_t merge_analysis;
    git_merge_file_favor_t merge_file_favor;
    git_merge_file_flag_t merge_file_flag;
    git_merge_flag_t merge_flag;
    git_merge_preference_t merge_preference;
    git_otype otype;
    git_pathspec_flag_t pathspec_flag;
    git_proxy_t proxy;
    git_remote_autotag_option_t remote_autotag_option;
    git_repository_state_t repository_state;
    git_reset_t reset;
    git_status_opt_t status_opt;
    git_status_show_t status_show;
    git_status_t status;
    git_sort_t sort;
    git_submodule_status_t submodule_status;
    git_submodule_ignore_t submodule_ignore;
    git_submodule_recurse_t submodule_recurse;
    git_submodule_update_t submodule_update;
    int stage;
    git_diff_find_t diff_find;
} esym_enumval;

typedef struct {
    emacs_value *symbol;
    esym_enumval value;
} esym_map;

extern esym_map esym_blame_flag_map[8];
extern esym_map esym_branch_map[4];
extern esym_map esym_cert_ssh_map[3];
extern esym_map esym_cert_map[5];
extern esym_map esym_checkout_notify_map[8];
extern esym_map esym_checkout_strategy_map[5];
extern esym_map esym_config_level_map[7];
extern esym_map esym_credtype_map[8];
extern esym_map esym_describe_strategy_map[5];
extern esym_map esym_delta_map[12];
extern esym_map esym_diff_format_map[7];
extern esym_map esym_diff_option_map[30];
extern esym_map esym_direction_map[3];
extern esym_map esym_error_map[34];
extern esym_map esym_feature_map[5];
extern esym_map esym_fetch_prune_map[5];
extern esym_map esym_filemode_map[7];
extern esym_map esym_index_add_option_map[5];
extern esym_map esym_indexcap_map[5];
extern esym_map esym_merge_analysis_map[6];
extern esym_map esym_merge_file_favor_map[5];
extern esym_map esym_merge_file_flag_map[10];
extern esym_map esym_merge_flag_map[5];
extern esym_map esym_merge_preference_map[4];
extern esym_map esym_otype_map[7];
extern esym_map esym_pathspec_flag_map[7];
extern esym_map esym_proxy_map[5];
extern esym_map esym_remote_autotag_option_map[5];
extern esym_map esym_repository_state_map[13];
extern esym_map esym_reset_map[4];
extern esym_map esym_status_opt_map[17];
extern esym_map esym_status_show_map[5];
extern esym_map esym_status_map[15];
extern esym_map esym_sort_map[5];
extern esym_map esym_submodule_status_map[15];
extern esym_map esym_submodule_ignore_map[6];
extern esym_map esym_submodule_recurse_map[4];
extern esym_map esym_submodule_update_map[5];
extern esym_map esym_stage_map[5];
extern esym_map esym_diff_find_map[15];
extern emacs_value esym_abbreviated_size;
extern emacs_value esym_abort;
extern emacs_value esym_added;
extern emacs_value esym_all;
extern emacs_value esym_always_use_long_format;
extern emacs_value esym_annotated_commit;
extern emacs_value esym_any;
extern emacs_value esym_app;
extern emacs_value esym_apply;
extern emacs_value esym_apply_mailbox;
extern emacs_value esym_apply_mailbox_or_rebase;
extern emacs_value esym_args_out_of_range;
extern emacs_value esym_assq;
extern emacs_value esym_auto;
extern emacs_value esym_base;
extern emacs_value esym_baseline;
extern emacs_value esym_bisect;
extern emacs_value esym_blame;
extern emacs_value esym_blame_hunk;
extern emacs_value esym_blob;
extern emacs_value esym_blob_executable;
extern emacs_value esym_break_rewrites;
extern emacs_value esym_break_rewrites_for_renames_only;
extern emacs_value esym_break_rewrite_threshold;
extern emacs_value esym_callbacks;
extern emacs_value esym_car;
extern emacs_value esym_cdr;
extern emacs_value esym_certificate_check;
extern emacs_value esym_check_pathspec;
extern emacs_value esym_checkout;
extern emacs_value esym_cherrypick;
extern emacs_value esym_cherrypick_sequence;
extern emacs_value esym_commit;
extern emacs_value esym_config;
extern emacs_value esym_conflict;
extern emacs_value esym_conflicted;
extern emacs_value esym_cons;
extern emacs_value esym_consp;
extern emacs_value esym_context_lines;
extern emacs_value esym_copied;
extern emacs_value esym_copy_threshold;
extern emacs_value esym_cred;
extern emacs_value esym_credentials;
extern emacs_value esym_current;
extern emacs_value esym_decode_time;
extern emacs_value esym_defalias;
extern emacs_value esym_default;
extern emacs_value esym_default_directory;
extern emacs_value esym_default_driver;
extern emacs_value esym_define_error;
extern emacs_value esym_deleted;
extern emacs_value esym_diff;
extern emacs_value esym_diff_binary;
extern emacs_value esym_diff_delta;
extern emacs_value esym_diff_hunk;
extern emacs_value esym_diff_line;
extern emacs_value esym_direct;
extern emacs_value esym_dirty;
extern emacs_value esym_dirty_suffix;
extern emacs_value esym_disable_pathspec_match;
extern emacs_value esym_download_tags;
extern emacs_value esym_enable_fast_untracked_dirs;
extern emacs_value esym_encode_time;
extern emacs_value esym_exclude_submodules;
extern emacs_value esym_expand_file_name;
extern emacs_value esym_fail_on_conflict;
extern emacs_value esym_failures_only;
extern emacs_value esym_fastforward;
extern emacs_value esym_fastforward_only;
extern emacs_value esym_fetch;
extern emacs_value esym_file_favor;
extern emacs_value esym_file_flags;
extern emacs_value esym_find_all;
extern emacs_value esym_find_copies;
extern emacs_value esym_find_copies_from_unmodified;
extern emacs_value esym_find_dont_ignore_whitespace;
extern emacs_value esym_find_exact_match_only;
extern emacs_value esym_find_failures;
extern emacs_value esym_find_for_untracked;
extern emacs_value esym_find_ignore_leading_whitespace;
extern emacs_value esym_find_ignore_whitespace;
extern emacs_value esym_find_remove_unmodified;
extern emacs_value esym_find_renames;
extern emacs_value esym_find_renames_from_rewrites;
extern emacs_value esym_find_rewrites;
extern emacs_value esym_first_parent;
extern emacs_value esym_flags;
extern emacs_value esym_force;
extern emacs_value esym_force_binary;
extern emacs_value esym_force_text;
extern emacs_value esym_from_owner;
extern emacs_value esym_functionp;
extern emacs_value esym_giterr;
extern emacs_value esym_giterr_callback;
extern emacs_value esym_giterr_checkout;
extern emacs_value esym_giterr_cherrypick;
extern emacs_value esym_giterr_config;
extern emacs_value esym_giterr_describe;
extern emacs_value esym_giterr_fetchhead;
extern emacs_value esym_giterr_filesystem;
extern emacs_value esym_giterr_filter;
extern emacs_value esym_giterr_index;
extern emacs_value esym_giterr_indexer;
extern emacs_value esym_giterr_invalid;
extern emacs_value esym_giterr_merge;
extern emacs_value esym_giterr_net;
extern emacs_value esym_giterr_nomemory;
extern emacs_value esym_giterr_object;
extern emacs_value esym_giterr_odb;
extern emacs_value esym_giterr_os;
extern emacs_value esym_giterr_patch;
extern emacs_value esym_giterr_rebase;
extern emacs_value esym_giterr_reference;
extern emacs_value esym_giterr_regex;
extern emacs_value esym_giterr_repository;
extern emacs_value esym_giterr_revert;
extern emacs_value esym_giterr_sha1;
extern emacs_value esym_giterr_ssh;
extern emacs_value esym_giterr_ssl;
extern emacs_value esym_giterr_stash;
extern emacs_value esym_giterr_submodule;
extern emacs_value esym_giterr_tag;
extern emacs_value esym_giterr_thread;
extern emacs_value esym_giterr_tree;
extern emacs_value esym_giterr_worktree;
extern emacs_value esym_giterr_zlib;
extern emacs_value esym_global;
extern emacs_value esym_hard;
extern emacs_value esym_headers;
extern emacs_value esym_hostkey_libssh2;
extern emacs_value esym_https;
extern emacs_value esym_id_abbrev;
extern emacs_value esym_ignore_case;
extern emacs_value esym_ignore_filemode;
extern emacs_value esym_ignore_submodules;
extern emacs_value esym_ignore_whitespace;
extern emacs_value esym_ignore_whitespace_change;
extern emacs_value esym_ignore_whitespace_eol;
extern emacs_value esym_ignored;
extern emacs_value esym_in_config;
extern emacs_value esym_in_head;
extern emacs_value esym_in_index;
extern emacs_value esym_in_wd;
extern emacs_value esym_include_casechange;
extern emacs_value esym_include_ignored;
extern emacs_value esym_include_typechange;
extern emacs_value esym_include_typechange_trees;
extern emacs_value esym_include_unmodified;
extern emacs_value esym_include_unreadable;
extern emacs_value esym_include_unreadable_as_untracked;
extern emacs_value esym_include_untracked;
extern emacs_value esym_indent_heuristic;
extern emacs_value esym_index;
extern emacs_value esym_index_added;
extern emacs_value esym_index_and_workdir;
extern emacs_value esym_index_deleted;
extern emacs_value esym_index_entry;
extern emacs_value esym_index_modified;
extern emacs_value esym_index_new;
extern emacs_value esym_index_only;
extern emacs_value esym_index_renamed;
extern emacs_value esym_index_typechange;
extern emacs_value esym_insert;
extern emacs_value esym_integerp;
extern emacs_value esym_interhunk_lines;
extern emacs_value esym_last;
extern emacs_value esym_length;
extern emacs_value esym_libgit_annotated_commit_p;
extern emacs_value esym_libgit_blame_hunk_p;
extern emacs_value esym_libgit_blame_p;
extern emacs_value esym_libgit_blob_p;
extern emacs_value esym_libgit_commit_p;
extern emacs_value esym_libgit_config_p;
extern emacs_value esym_libgit_cred_p;
extern emacs_value esym_libgit_diff_binary_p;
extern emacs_value esym_libgit_diff_delta_p;
extern emacs_value esym_libgit_diff_hunk_p;
extern emacs_value esym_libgit_diff_line_p;
extern emacs_value esym_libgit_diff_p;
extern emacs_value esym_libgit_index_entry_p;
extern emacs_value esym_libgit_index_p;
extern emacs_value esym_libgit_object_p;
extern emacs_value esym_libgit_pathspec_match_list_p;
extern emacs_value esym_libgit_pathspec_p;
extern emacs_value esym_libgit_reference_p;
extern emacs_value esym_libgit_reflog_entry_p;
extern emacs_value esym_libgit_reflog_p;
extern emacs_value esym_libgit_refspec_p;
extern emacs_value esym_libgit_remote_p;
extern emacs_value esym_libgit_repository_p;
extern emacs_value esym_libgit_revwalk_p;
extern emacs_value esym_libgit_signature_p;
extern emacs_value esym_libgit_submodule_p;
extern emacs_value esym_libgit_tag_p;
extern emacs_value esym_libgit_transaction_p;
extern emacs_value esym_libgit_tree_p;
extern emacs_value esym_libgit_treebuilder_p;
extern emacs_value esym_link;
extern emacs_value esym_list;
extern emacs_value esym_listp;
extern emacs_value esym_local;
extern emacs_value esym_max_candidates_tags;
extern emacs_value esym_max_line;
extern emacs_value esym_max_size;
extern emacs_value esym_md5;
extern emacs_value esym_merge;
extern emacs_value esym_metric;
extern emacs_value esym_min_line;
extern emacs_value esym_minimal;
extern emacs_value esym_mixed;
extern emacs_value esym_modified;
extern emacs_value esym_name_only;
extern emacs_value esym_name_status;
extern emacs_value esym_new;
extern emacs_value esym_new_prefix;
extern emacs_value esym_newest_commit;
extern emacs_value esym_nil;
extern emacs_value esym_no_fastforward;
extern emacs_value esym_no_filemode;
extern emacs_value esym_no_glob;
extern emacs_value esym_no_match_error;
extern emacs_value esym_no_recursive;
extern emacs_value esym_no_refresh;
extern emacs_value esym_no_symlinks;
extern emacs_value esym_none;
extern emacs_value esym_normal;
extern emacs_value esym_notify;
extern emacs_value esym_notify_when;
extern emacs_value esym_nsec;
extern emacs_value esym_object;
extern emacs_value esym_off;
extern emacs_value esym_old;
extern emacs_value esym_old_prefix;
extern emacs_value esym_oldest_commit;
extern emacs_value esym_on;
extern emacs_value esym_ondemand;
extern emacs_value esym_only_follow_first_parent;
extern emacs_value esym_ours;
extern emacs_value esym_patch;
extern emacs_value esym_patch_header;
extern emacs_value esym_pathspec;
extern emacs_value esym_pathspec_match_list;
extern emacs_value esym_patience;
extern emacs_value esym_pattern;
extern emacs_value esym_post;
extern emacs_value esym_pre;
extern emacs_value esym_programdata;
extern emacs_value esym_progress;
extern emacs_value esym_provide;
extern emacs_value esym_proxy;
extern emacs_value esym_prune;
extern emacs_value esym_push;
extern emacs_value esym_raw;
extern emacs_value esym_rebase;
extern emacs_value esym_rebase_interactive;
extern emacs_value esym_rebase_merge;
extern emacs_value esym_recurse_ignored_dirs;
extern emacs_value esym_recurse_untracked_dirs;
extern emacs_value esym_recursion_limit;
extern emacs_value esym_reference;
extern emacs_value esym_reflog;
extern emacs_value esym_reflog_entry;
extern emacs_value esym_refspec;
extern emacs_value esym_remote;
extern emacs_value esym_rename_threshold;
extern emacs_value esym_rename_from_rewrite_threshold;
extern emacs_value esym_rename_limit;
extern emacs_value esym_rename_threshold;
extern emacs_value esym_renamed;
extern emacs_value esym_renames_from_rewrites;
extern emacs_value esym_renames_head_to_index;
extern emacs_value esym_renames_index_to_workdir;
extern emacs_value esym_repository;
extern emacs_value esym_reverse;
extern emacs_value esym_revert;
extern emacs_value esym_revert_sequence;
extern emacs_value esym_revwalk;
extern emacs_value esym_safe;
extern emacs_value esym_sha1;
extern emacs_value esym_show_binary;
extern emacs_value esym_show_commit_oid_as_fallback;
extern emacs_value esym_show_unmodified;
extern emacs_value esym_show_untracked_content;
extern emacs_value esym_sideband_progress;
extern emacs_value esym_signature;
extern emacs_value esym_simplify_alnum;
extern emacs_value esym_skip;
extern emacs_value esym_skip_binary_check;
extern emacs_value esym_skip_reuc;
extern emacs_value esym_soft;
extern emacs_value esym_sort_case_insensitively;
extern emacs_value esym_sort_case_sensitively;
extern emacs_value esym_specified;
extern emacs_value esym_ssh;
extern emacs_value esym_ssh_custom;
extern emacs_value esym_ssh_interactive;
extern emacs_value esym_ssh_key;
extern emacs_value esym_ssh_memory;
extern emacs_value esym_strarray;
extern emacs_value esym_strategy;
extern emacs_value esym_string_as_unibyte;
extern emacs_value esym_stringp;
extern emacs_value esym_style_diff3;
extern emacs_value esym_style_merge;
extern emacs_value esym_submodule;
extern emacs_value esym_symbol_value;
extern emacs_value esym_symbolic;
extern emacs_value esym_system;
extern emacs_value esym_t;
extern emacs_value esym_tag;
extern emacs_value esym_tags;
extern emacs_value esym_target_limit;
extern emacs_value esym_theirs;
extern emacs_value esym_threads;
extern emacs_value esym_time;
extern emacs_value esym_topological;
extern emacs_value esym_track_copies_any_commit_copies;
extern emacs_value esym_track_copies_same_commit_copies;
extern emacs_value esym_track_copies_same_commit_moves;
extern emacs_value esym_track_copies_same_file;
extern emacs_value esym_transaction;
extern emacs_value esym_transfer_progress;
extern emacs_value esym_tree;
extern emacs_value esym_treebuilder;
extern emacs_value esym_type;
extern emacs_value esym_typechange;
extern emacs_value esym_unborn;
extern emacs_value esym_union;
extern emacs_value esym_unmodified;
extern emacs_value esym_unreadable;
extern emacs_value esym_unspecified;
extern emacs_value esym_untracked;
extern emacs_value esym_up_to_date;
extern emacs_value esym_update_fetchhead;
extern emacs_value esym_update_index;
extern emacs_value esym_updated;
extern emacs_value esym_url;
extern emacs_value esym_use_case;
extern emacs_value esym_use_mailmap;
extern emacs_value esym_user_ptrp;
extern emacs_value esym_username;
extern emacs_value esym_userpass_plaintext;
extern emacs_value esym_vector;
extern emacs_value esym_wd_added;
extern emacs_value esym_wd_deleted;
extern emacs_value esym_wd_index_modified;
extern emacs_value esym_wd_modified;
extern emacs_value esym_wd_uninitialized;
extern emacs_value esym_wd_untracked;
extern emacs_value esym_wd_wd_modified;
extern emacs_value esym_workdir_only;
extern emacs_value esym_wrong_type_argument;
extern emacs_value esym_wrong_value_argument;
extern emacs_value esym_wt_deleted;
extern emacs_value esym_wt_modified;
extern emacs_value esym_wt_new;
extern emacs_value esym_wt_renamed;
extern emacs_value esym_wt_typechange;
extern emacs_value esym_wt_unreadable;
extern emacs_value esym_x509;
extern emacs_value esym_xdg;

void esyms_init(emacs_env *env);

#endif /* SYMBOLS_H */
